apiVersion: v1
kind: Secret
metadata:
  name: stonks-api-key
type: Opaque
data:
  key: "demo"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stonks-config
data:
  symbol: "MSFT"
  ndays: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stonks
  name: stonks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stonks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stonks
    spec:
      containers:
      - image: docker.io/epequeno/stonks
        name: stonks
        ports:
          - containerPort: 8000
        resources: {}
        env:
          - name: SYMBOL
            valueFrom:
              configMapKeyRef:
                name: stonks-config
                key: symbol
          - name: NDAYS
            valueFrom:
              configMapKeyRef:
                name: stonks-config
                key: ndays
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: stonks-api-key
                key: key
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: stonks
spec:
  type: NodePort
  selector:
    app: stonks
  ports:
    - port: 8000
      nodePort: 30007